### ISSUE TITLE
Proposal: add Service to each application

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-incubator/eirini-release#132]
Towards allowing `cf push` applications to become more native to Kubernetes, I'd like to propose that each application also includes a Service.

An example manually created Service example below:

```
$ curl sample-app-nodejs-dev-d50e44dc8d.scf-eirini.svc.cluster.local:8080
Hello World!

$ kubectl get all -n scf-eirini
NAME                                     READY   STATUS    RESTARTS   AGE
pod/kwt-net                              1/1     Running   0          8m32s
pod/sample-app-nodejs-dev-bcb9c9b5a7-0   1/1     Running   0          52s
pod/sample-app-nodejs-dev-bcb9c9b5a7-1   1/1     Running   0          52s
pod/sample-app-nodejs-dev-bcb9c9b5a7-2   0/1     Running   0          52s

NAME                                       TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)    AGE
service/sample-app-nodejs-dev-d50e44dc8d   ClusterIP   10.12.2.168   <none>        8080/TCP   10m

NAME                                                READY   AGE
statefulset.apps/sample-app-nodejs-dev-bcb9c9b5a7   2/3     54s
```

The definition of the service would bind to the `guid` label on the application, such as:

```yaml
# Idea for an Eirini service mapping to a CF app's pods
# `cf app sample-app-nodejs --guid`
# => 51c11bc3-f2ce-407a-836d-b5bd66847f74
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    guid: 51c11bc3-f2ce-407a-836d-b5bd66847f74
  name: sample-app-nodejs-dev-d50e44dc8d
  namespace: scf-eirini
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    guid: 51c11bc3-f2ce-407a-836d-b5bd66847f74
  type: ClusterIP
status:
  loadBalancer: {}
```

Would there be risks/downsides to including a Service with each application?

Maybe this is only half a feature - what is the right & useful name for the service etc; what annotations to attach; what are the range of use cases?

I could investigate an implementation (ooh via eirinix maybe) if you're ok with this proposal.
