### ISSUE TITLE
Released UAA chart 2.18.0 has broken apiVersion

### ISSUE THREAD

**Issue by aegershman** [cloudfoundry-incubator/eirini-release#139]
https://github.com/cloudfoundry-incubator/eirini-release/commit/bd83ac842139a4ac5c1c622ee36432df4473bf71

This resolved the `apiVersion` in the codebase but the released version of `2.18.0` still has the broken apiVersion

```sh
helm fetch eirini/uaa --version 2.18.0
```

```yml
# Chart.yml
apiVersion: 2.18.0+cf9.5.0.0.ga2697c75
appVersion: 1.5.0
description: A Helm chart for SUSE UAA
name: uaa
version: 2.18.0
```

which means `helm` can't install it

```sh
  Error: apiVersion '2.18.0+cf9.5.0.0.ga2697c75' is not valid. The value must be "v1"
```

Can the UAA chart be bumped to 2.18.1 and cut with a release with the fixed apiVersion? 

I'll just make a local copy of the chart in the mean time, it's not a big deal.

Thanks for your time 👍
